name: the_monkslab_web
description: A web platform to learn, teach and connect
publish_to: 'none'

version: 0.0.0+4

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  beamer: ^1.5.0
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.10+2
  flutter_svg: ^1.1.1+1
  formz: ^0.4.1
  freezed_annotation: ^2.0.3
  google_fonts: ^3.0.1
  http_mock_adapter: ^0.3.2
  intl: ^0.17.0
  json_serializable: ^6.2.0

  rxdart: ^0.27.4
  user_repository:
    path: packages/user_repository
  url_launcher: ^6.1.4


dev_dependencies:
  bloc_test: ^9.1.0
  mocktail: ^0.3.0
  build_runner: ^2.1.11
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/logos/
