name: the_monkslab_web
description: A web platform to learn, teach and connect
publish_to: "none"

version: 0.0.0+4

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  beamer: ^1.5.3
  cloud_firestore: ^4.4.4
  dio: ^5.0.1
  equatable: ^2.0.5
  firebase_core: ^2.7.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_highlight: ^0.7.0
  flutter_html: ^3.0.0-alpha.6
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.6
  google_fonts: ^4.0.3
  intl: ^0.18.0
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4
  localization: ^2.1.0
  markdown: ^7.0.1
  mocktail: ^0.3.0
  provider: ^6.0.5
  url_launcher: ^6.1.10

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.3.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/
    - assets/images/logos/
    - assets/translations/
    - lib/i18n/
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/montserrat/montserrat_regular.ttf
        - asset: fonts/montserrat/montserrat_italic.ttf
          style: italic
        - asset: fonts/montserrat/montserrat_bold.ttf
          weight: 700
        - asset: fonts/montserrat/montserrat_bold_italic.ttf
          style: italic
          weight: 700
