name: the_monkslab_web
description: A web platform to learn, teach and connect
publish_to: 'none'

version: 0.0.0+4

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  beamer: ^1.5.3
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.6
  freezed: ^2.2.0
  freezed_annotation: ^2.2.0
  google_fonts: ^3.0.1
  intl: ^0.17.0
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4
  url_launcher: ^6.1.7
  firebase_core: ^2.3.0
  cloud_firestore: ^4.1.0
  markdown: ^6.0.1
  flutter_html: ^3.0.0-alpha.5
  flutter_highlight: ^0.7.0
  mocktail: ^0.3.0
  equatable: ^2.0.5

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.3.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/logos/
    - assets/courses/
