name: the_monkslab_web
description: A web platform to learn, teach and connect
publish_to: 'none'

version: 0.0.0+3

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.10+2
  flutter_svg: ^1.1.1+1
  freezed_annotation: ^2.0.3
  google_fonts: ^3.0.1
  http_mock_adapter: ^0.3.2
  json_serializable: ^6.2.0
  mocktail: ^0.3.0
  rxdart: ^0.27.4
  url_launcher: ^6.1.4
  
dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/logos/
