// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGOVRyABKzyN1sK8bfw95e1YaCY4aQrCw',
    appId: '1:837553242957:web:5d207458020ebd1bedad04',
    messagingSenderId: '837553242957',
    projectId: 'monsklab-courses',
    authDomain: 'monsklab-courses.firebaseapp.com',
    storageBucket: 'monsklab-courses.appspot.com',
    measurementId: 'G-T4QMR5W0FB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-_XQi3bgqzX74q4i2k3LR3O-VNl5eL1I',
    appId: '1:837553242957:android:c98b4af966e93761edad04',
    messagingSenderId: '837553242957',
    projectId: 'monsklab-courses',
    storageBucket: 'monsklab-courses.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0CJhRUlWJhERnh3WaM7UmrPTltP2re3Y',
    appId: '1:837553242957:ios:b4f2853a1c1aa451edad04',
    messagingSenderId: '837553242957',
    projectId: 'monsklab-courses',
    storageBucket: 'monsklab-courses.appspot.com',
    iosClientId: '837553242957-rv87kul03luqnhbo1pgba236n15rb6aj.apps.googleusercontent.com',
    iosBundleId: 'com.example.theMonkslabWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0CJhRUlWJhERnh3WaM7UmrPTltP2re3Y',
    appId: '1:837553242957:ios:b4f2853a1c1aa451edad04',
    messagingSenderId: '837553242957',
    projectId: 'monsklab-courses',
    storageBucket: 'monsklab-courses.appspot.com',
    iosClientId: '837553242957-rv87kul03luqnhbo1pgba236n15rb6aj.apps.googleusercontent.com',
    iosBundleId: 'com.example.theMonkslabWeb',
  );
}
