// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqvkxMKfc79yStUahHWwrouQR3cx4htII',
    appId: '1:894604238429:web:4351e3065dfa2b0d72f7b4',
    messagingSenderId: '894604238429',
    projectId: 'the-monkslab-web-tests',
    authDomain: 'the-monkslab-web-tests.firebaseapp.com',
    storageBucket: 'the-monkslab-web-tests.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiIJRMYDIIdRjqAEWCOpGGR4MhS0sMcyM',
    appId: '1:894604238429:android:9a39c7f1894c76aa72f7b4',
    messagingSenderId: '894604238429',
    projectId: 'the-monkslab-web-tests',
    storageBucket: 'the-monkslab-web-tests.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnL5x4iXdEvIvGAR5Ffm_mqEwvyWVwgYg',
    appId: '1:894604238429:ios:6215eac62fec80bd72f7b4',
    messagingSenderId: '894604238429',
    projectId: 'the-monkslab-web-tests',
    storageBucket: 'the-monkslab-web-tests.appspot.com',
    iosClientId: '894604238429-r58vmgqpj6irrg187obqh072nbkocp1q.apps.googleusercontent.com',
    iosBundleId: 'com.example.theMonkslabWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnL5x4iXdEvIvGAR5Ffm_mqEwvyWVwgYg',
    appId: '1:894604238429:ios:6215eac62fec80bd72f7b4',
    messagingSenderId: '894604238429',
    projectId: 'the-monkslab-web-tests',
    storageBucket: 'the-monkslab-web-tests.appspot.com',
    iosClientId: '894604238429-r58vmgqpj6irrg187obqh072nbkocp1q.apps.googleusercontent.com',
    iosBundleId: 'com.example.theMonkslabWeb',
  );
}
