// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3-tT7LORnOFcxGWcbvAsd-3zXdGcCEY0',
    appId: '1:1056886643362:web:9a15011c639436cc8295fb',
    messagingSenderId: '1056886643362',
    projectId: 'monkslab-courses',
    authDomain: 'monkslab-courses.firebaseapp.com',
    storageBucket: 'monkslab-courses.appspot.com',
    measurementId: 'G-1D1MYMH3ST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN06QfL8l3AfBa9zkxopHVL8o9i2L3Ioc',
    appId: '1:1056886643362:android:fc01275ff07d02998295fb',
    messagingSenderId: '1056886643362',
    projectId: 'monkslab-courses',
    storageBucket: 'monkslab-courses.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVlggRLri0rg1NZdl4gGFqMp3Hbq7zXwc',
    appId: '1:1056886643362:ios:6932d5d21d8eeefb8295fb',
    messagingSenderId: '1056886643362',
    projectId: 'monkslab-courses',
    storageBucket: 'monkslab-courses.appspot.com',
    iosClientId: '1056886643362-favha8att8f56m4b7dfok3cdrvgivdq6.apps.googleusercontent.com',
    iosBundleId: 'com.example.theMonkslabWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVlggRLri0rg1NZdl4gGFqMp3Hbq7zXwc',
    appId: '1:1056886643362:ios:6932d5d21d8eeefb8295fb',
    messagingSenderId: '1056886643362',
    projectId: 'monkslab-courses',
    storageBucket: 'monkslab-courses.appspot.com',
    iosClientId: '1056886643362-favha8att8f56m4b7dfok3cdrvgivdq6.apps.googleusercontent.com',
    iosBundleId: 'com.example.theMonkslabWeb',
  );
}
