name: courses_repository
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.19.0-255.2.beta <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  freezed: ^2.2.0
  freezed_annotation: ^2.0.3
  json_annotation: ^4.7.0
  json_serializable: ^6.2.0
  mocktail: ^0.3.0
  rxdart: ^0.27.4
  github_api:
    path: ../github_api

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter


