name: Deploy Web to Production
on:
  workflow_dispatch:
  workflow_call:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: |
          flutter pub get
          flutter build web
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_MONSKLAB_COURSES }}"
          channelId: live
          projectId: monsklab-courses
          target: the-monkslab-site
